---
site_name: Fortigate Terraform Deploy
site_description: Deployment templates for FortiGate-VM on cloud platforms with terraform
site_url: https://robinmordasiewicz.github.io/fortigate-terraform-deploy/
repo_url: https://github.com/robinmordasiewicz/fortigate-terraform-deploy/
edit_uri: edit/main/docs/
repo_name: "robinmordasiewicz/fortigate-terraform-deploy"

extra:
  generator: false

theme: material
  logo: fortinet.svg
  favicon: fortinet.svg
  custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/github
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.footer
    - navigation.indexes
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - navigation.path

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      toc_depth: "1-1"
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true

plugins:
  - git-committers:
      repository: robinmordasiewicz/fortigate-azure-terraform
      branch: main
  - glightbox
  - social
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

nav:
  - Home: index.md
